The following line threw a NotImplementedError exception: answer_question4b:
bad_tags, good_tags, answer4b = answer_question4b()
-------
The following line threw a NameError exception: name 'bad_tags' is not defined:
print(bad_tags)
-------
The following line threw a NameError exception: name 'good_tags' is not defined:
print(good_tags)
-------
The following line threw a NameError exception: name 'answer4b' is not defined:
print(answer4b[:280])
-------
The following line threw a NotImplementedError exception: answer_question5:
answer5 = answer_question5()
-------
The following line threw a NameError exception: name 'answer5' is not defined:
print(answer5[:500])
-------
The following line threw a NotImplementedError exception: answer_question6:
answer6 = answer_question6()
-------
The following line threw a NameError exception: name 'answer6' is not defined:
print(answer6[:500])
-------
Exception in answer dict value computation:
    bad_tags -> NameError("name 'bad_tags' is not defined")
  File "/afs/inf.ed.ac.uk/user/s18/s1841215/PycharmProjects/FNLP2/assignment2/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    good_tags -> NameError("name 'good_tags' is not defined")
  File "/afs/inf.ed.ac.uk/user/s18/s1841215/PycharmProjects/FNLP2/assignment2/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    answer4b -> NameError("name 'answer4b' is not defined")
  File "/afs/inf.ed.ac.uk/user/s18/s1841215/PycharmProjects/FNLP2/assignment2/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    min((model.get_viterbi_value(s,-1) for s in model.states)) if len(model.states)>0 else FAILED -> TypeError("'<' not supported between instances of 'NoneType' and 'NoneType'")
  File "/afs/inf.ed.ac.uk/user/s18/s1841215/PycharmProjects/FNLP2/assignment2/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    answer5 -> NameError("name 'answer5' is not defined")
  File "/afs/inf.ed.ac.uk/user/s18/s1841215/PycharmProjects/FNLP2/assignment2/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    answer6 -> NameError("name 'answer6' is not defined")
  File "/afs/inf.ed.ac.uk/user/s18/s1841215/PycharmProjects/FNLP2/assignment2/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
